// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcsGjdFfgwyLEVzPrWDHbDSerplPHUDLg',
    appId: '1:876369016425:web:f55121ae7b9a53fd8ad4f8',
    messagingSenderId: '876369016425',
    projectId: 'logincheckproject',
    authDomain: 'logincheckproject.firebaseapp.com',
    storageBucket: 'logincheckproject.appspot.com',
    measurementId: 'G-YS0M6XLZJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBPjkOY-apuS3Q9DRzCAAQBJuGEsXbwOs',
    appId: '1:876369016425:android:07dfb643102e594c8ad4f8',
    messagingSenderId: '876369016425',
    projectId: 'logincheckproject',
    storageBucket: 'logincheckproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmc07lQ412FHIIL2hfmLr9zz4oGUt4nac',
    appId: '1:876369016425:ios:fb01e0a6d659915f8ad4f8',
    messagingSenderId: '876369016425',
    projectId: 'logincheckproject',
    storageBucket: 'logincheckproject.appspot.com',
    iosClientId: '876369016425-1pvjg24hk5mtdjsnj8ttcbttedi81r7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterloginapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmc07lQ412FHIIL2hfmLr9zz4oGUt4nac',
    appId: '1:876369016425:ios:fb01e0a6d659915f8ad4f8',
    messagingSenderId: '876369016425',
    projectId: 'logincheckproject',
    storageBucket: 'logincheckproject.appspot.com',
    iosClientId: '876369016425-1pvjg24hk5mtdjsnj8ttcbttedi81r7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterloginapplication',
  );
}
